# Generated by Django 2.1.3 on 2018-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Should be one long string of parsed text', verbose_name='Document Text')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='File Name')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(verbose_name='Start Index')),
                ('end', models.IntegerField(verbose_name='End Index')),
                ('phrase', models.CharField(blank=True, max_length=250, verbose_name='Word or Phrase')),
                ('entity_type', models.CharField(blank=True, max_length=50, verbose_name='Entity Type')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='entities',
            field=models.ManyToManyField(blank=True, to='tool.Entity', verbose_name='Entities'),
        ),
    ]
