# Generated by Django 2.1.3 on 2018-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20181127_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
